# Generated by Django 5.1 on 2024-08-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('ratings_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('text_reviews_count', models.IntegerField(default=0)),
                ('fans_count', models.IntegerField(default=0)),
                ('works_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('work_id', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('isbn13', models.CharField(blank=True, max_length=13)),
                ('asin', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ratings_count', models.IntegerField(default=0)),
                ('text_reviews_count', models.IntegerField(default=0)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('original_publication_date', models.DateField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('edition_information', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('num_pages', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(related_name='books', to='libraryapi.author')),
            ],
        ),
        migrations.CreateModel(
            name='RatingDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_stars', models.IntegerField(default=0)),
                ('four_stars', models.IntegerField(default=0)),
                ('three_stars', models.IntegerField(default=0)),
                ('two_stars', models.IntegerField(default=0)),
                ('one_stars', models.IntegerField(default=0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_distribution', to='libraryapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('books', models.ManyToManyField(blank=True, related_name='series', to='libraryapi.book')),
            ],
        ),
    ]
