# Generated by Django 5.1 on 2024-08-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='books',
        ),
        migrations.DeleteModel(
            name='RatingDistribution',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
