# Generated by Django 5.1 on 2024-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0002_remove_series_books_delete_ratingdistribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
