# Generated by Django 5.1 on 2024-08-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0003_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_5', models.IntegerField(default=0)),
                ('rating_4', models.IntegerField(default=0)),
                ('rating_3', models.IntegerField(default=0)),
                ('rating_2', models.IntegerField(default=0)),
                ('rating_1', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('book_rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_distribution_details', to='libraryapi.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='rating_distribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='libraryapi.ratingdistribution'),
        ),
    ]
