# Generated by Django 5.1 on 2024-08-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0004_ratingdistribution_book_rating_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdistribution',
            name='book_rating',
        ),
    ]
