# Generated by Django 5.1 on 2024-08-20 07:51

import pgvector.django
from django.db import migrations
from pgvector.django import VectorExtension



class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0008_book_vector'),
    ]
    operations = [
        VectorExtension()
    ]
