# Generated by Django 5.1 on 2024-08-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0009_alter_book_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='vector',
        ),
    ]
