# Generated by Django 5.1 on 2024-08-20 09:18

import pgvector.django
from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0010_remove_book_vector'),
    ]

    # operations = [
    #     VectorExtension()
    # ]
    operations = [
        migrations.AddField(
            model_name='book',
            name='vector',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
