# Generated by Django 5.1 on 2024-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0011_book_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
